@baseUrl = http://localhost:3000
@userNorth = user-north
@userSouth = user-south
@userAdmin = user-admin

### Health check
GET {{baseUrl}}/health

### Listar projetos - Construtora Norte
GET {{baseUrl}}/projects
x-user-id: {{userNorth}}

### Listar projetos - Urbaniza Sul
GET {{baseUrl}}/projects
x-user-id: {{userSouth}}

### Listar projetos - Administrador global
GET {{baseUrl}}/projects
x-user-id: {{userAdmin}}

### Detalhe - Residencial Jardim das Palmeiras
GET {{baseUrl}}/projects/project-palmeiras
x-user-id: {{userSouth}}

### Detalhe - Loteamento Bela Vista
GET {{baseUrl}}/projects/project-bela-vista
x-user-id: {{userNorth}}

### Detalhe - Edificio Horizonte Sul
GET {{baseUrl}}/projects/project-horizonte-sul
x-user-id: {{userSouth}}

### Detalhe - Condominio Parque Linear
GET {{baseUrl}}/projects/project-parque-linear
x-user-id: {{userSouth}}

### Detalhe como administrador global
GET {{baseUrl}}/projects/project-horizonte-sul
x-user-id: {{userAdmin}}

### Documentos - Residencial Jardim das Palmeiras
GET {{baseUrl}}/projects/project-palmeiras/documents
x-user-id: {{userNorth}}

### Documentos - Loteamento Bela Vista
GET {{baseUrl}}/projects/project-bela-vista/documents
x-user-id: {{userNorth}}

### Documentos - Edificio Horizonte Sul
GET {{baseUrl}}/projects/project-horizonte-sul/documents
x-user-id: {{userSouth}}

### Documentos - Condominio Parque Linear
GET {{baseUrl}}/projects/project-parque-linear/documents
x-user-id: {{userSouth}}

### Sem autenticacao
GET {{baseUrl}}/projects
